### ISSUE TITLE
Could not find com.midtrans:corekit:1.21.2-SANDBOX.

### ISSUE THREAD

**Issue by umam006** [aldente05/react-native-payment-gateway#11]
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.midtrans:corekit:1.21.2-SANDBOX.
  Required by:
      project :app > project :react-native-payment-gateway
> Could not find com.midtrans:uikit:1.21.2-SANDBOX.
  Required by:
      project :app > project :react-native-payment-gateway

**Comment by herarya** [comment]
hi @umam006 try to add this to android/build.gradle

```java
 // Add the midtrans repository into the list of repositories
maven { url "http://dl.bintray.com/pt-midtrans/maven" }
```
