### ISSUE TITLE
* What went wrong: Execution failed for task ':react-native-payment-gateway:verifyReleaseResources'. > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

### ISSUE THREAD

**Issue by umam006** [aldente05/react-native-payment-gateway#12]
* What went wrong:
Execution failed for task ':react-native-payment-gateway:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  warn: removing resource com.paymentgateway:string/title_payment_failed without required default value.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values/values.xml:3860: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values/values.xml:4316: error: resource android:attr/keyboardNavigationCluster not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values/values.xml:5187: error: resource android:attr/fontStyle not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values/values.xml:5188: error: resource android:attr/font not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values/values.xml:5189: error: resource android:attr/fontWeight not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values/values.xml:5190: error: resource android:attr/fontVariationSettings not found.
  /home/umam/project/baligatra/beetle/node_modules/react-native-payment-gateway/android/build/intermediates/res/merged/release/values/values.xml:5191: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by akbarumar88** [comment]
Have you resolved this issue broh ??? @umam006

**Comment by akbarumar88** [comment]
Hello brothers, i have resolved by using https://www.npmjs.com/package/react-native-midtrans-payment-gateway instead 😄

**Comment by snelanga** [comment]
You can fix this by updating the Gradle version of the library itself.
You can check the changes here in my forked project.
[https://github.com/snelanga/react-native-payment-gateway](https://github.com/snelanga/react-native-payment-gateway)
