### ISSUE TITLE
App Force close when attempting checking out transactions using atm / brank transfer

### ISSUE THREAD

**Issue by akbarumar88** [aldente05/react-native-payment-gateway#14]
**Description**
Hi guys
when i tried to checkout my transaction in sandbox environment, selecting the atm / bank transfer payment method, i got the app crashed, but the another payment works

![midtrans_crashed](https://user-images.githubusercontent.com/37323715/61791608-ae7dcd00-ae44-11e9-9f05-7e4a4bc66d64.PNG)

**Environment**
"react-native": "^0.57.8"
"react": "16.7.0"

Can u guys please help me for my continue  app development
and @aldente05 @radiegtya @knax please help me for this, is there anything missing in my project
or need another libs to implement this package

Thanks in advance :D

**Comment by knax** [comment]
Hello @akbarumar88 can you provide us with more information? Can you post the logcat when the error occured?

**Comment by akbarumar88** [comment]
> Hello @akbarumar88 can you provide us with more information? Can you post the logcat when the error occured?

Hi @knax I'm using react native here, but when the app got force closed, i didn't notice any error message in my logcat

![midtrans-err-logcat](https://user-images.githubusercontent.com/37323715/61798815-2ef7fa00-ae54-11e9-894c-569932fd821f.PNG)

it just shows usual log, btw what's the difference between @aldente05 's react-native-payment-gateway and your @knax / react-native-midtrans you forked, does it solve some errors and bugs ?

thanks in advance 👍

**Comment by knax** [comment]
Hi @akbarumar88 can you show us the complete logcat, don't filter it by 
adb logcat *:S ReactNative:V ReactNativeJS:V

The error should be on native side, not on the JS code, so if you filter it by ReactNative:V the error will not shown.

I've added direct payment to react-native-midtrans, so you can directly send user to specific payment type.

Btw its been a long time ago since I've maintain the repo, so I don't know if its still works or not in latest react native version 😆

So if you encounter any error or bugs, feel free to mention me 😉

**Comment by akbarumar88** [comment]
> Hi @akbarumar88 can you show us the complete logcat, don't filter it by
> adb logcat *:S ReactNative:V ReactNativeJS:V
> 
> The error should be on native side, not on the JS code, so if you filter it by ReactNative:V the error will not shown.
> 
> I've added direct payment to react-native-midtrans, so you can directly send user to specific payment type.
> 
> Btw its been a long time ago since I've maintain the repo, so I don't know if its still works or not in latest react native version 😆
> 
> So if you encounter any error or bugs, feel free to mention me 😉

Thanks buddy @knax , You helped me a lot, you teach me how to log android completely, and you teach me the differs between your forked repo and the original one, cuz when i tried the sample sdk kit in the java version it could select method manually without showing another payment mehtod, i thought that it doesn't available in this react native version :D

BTW And the app is working now :D, is there any mistake in your docs ? cuz i see 
`include ':react-native-payment-gateway'
project(':react-native-payment-gateway').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-payment-gateway/android')`
isn't that supposed to be
`include ':react-native-payment-gateway'
project(':react-native-payment-gateway').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-payment-gateway/android')`

Because instead of using your libs it was using @aldente05 's original library :D
Hope you also update your docs, so that the other beginners can use or libs as easy as possible 

Thanks in advance
