### ISSUE TITLE
Error when building release 

### ISSUE THREAD

**Issue by akbarumar88** [aldente05/react-native-payment-gateway#15]
Hello I'm Akbar a React Native developer. Your library is really great !, i really like it. But i'm facing an issue when building my app into release, but it works fine on debug without any problem. I've never build my app into release so i just know that there's an issue when building it into release.

React Native version : 0.60.4
Lib Version i use : ^0.4.3

The error looks like something like this

> Execution failed for task ':react-native-payment-gateway:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  warn: removing resource com.paymentgateway:string/title_payment_failed without required default value.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values\values.xml:3883: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values\values.xml:4339: error: resource android:attr/keyboardNavigationCluster not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values\values.xml:5210: error: resource android:attr/fontStyle not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values\values.xml:5211: error: resource android:attr/font not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values\values.xml:5212: error: resource android:attr/fontWeight not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values\values.xml:5213: error: resource android:attr/fontVariationSettings not found.
  D:\Project ICT\devmedismobcode\node_modules\react-native-payment-gateway\android\build\intermediates\res\merged\release\values\values.xml:5214: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

I'm hoping so much for your attention about this issue because i really need this to continue my app development 😄 
Thanks For Your attention 😃 
@radiegtya @aldente05 @knax

**Comment by snelanga** [comment]
You can fix this by updating the Gradle version of the library itself.
You can check the changes here in my forked project.
[https://github.com/snelanga/react-native-payment-gateway](https://github.com/snelanga/react-native-payment-gateway)
