### ISSUE TITLE
Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by lexdorf-17** [aldente05/react-native-payment-gateway#16]
Halo gan, Ketika masuk k screen Midtrans keluar error tersebut Thread 1: signal SIGABRT

**Comment by aldente05** [comment]
@dedenhendrap halo, tolong lampirkan screenshoot terkait error tsb

**Comment by lexdorf-17** [comment]
sepertinya sama kaya d grup mas terkait status bar

**Comment by lexdorf-17** [comment]
ada warning d modulenya mas Class 'MidtransModule' does not conform to protocol 'MidtransUIPaymentViewCo

**Comment by lexdorf-17** [comment]
![image](https://user-images.githubusercontent.com/31558217/71968842-36f7fa80-3238-11ea-9269-13203adde599.png)
 ini mas capturenya
