### ISSUE TITLE
 Could not find method api() for arguments

### ISSUE THREAD

**Issue by sandropoluan** [aldente05/react-native-payment-gateway#3]
* What went wrong:
A problem occurred evaluating project ':react-native-payment-gateway'.
> Could not find method api() for arguments [com.midtrans:corekit:1.15.0-SANDBOX] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by aldente05** [comment]
solve on version 0.4.3
