### ISSUE TITLE
Revision on Documentation section Android

### ISSUE THREAD

**Issue by cwicaksono** [aldente05/react-native-payment-gateway#8]
On documentation you write on section Android that we must open `MainActivity.java` but when I search that file there is no method that called `getPackages()`

Maybe the file that with method is `MainApplication.java`, on this file we can find method `getPackages()`

thank you

**Comment by aldente05** [comment]
thanks for your information.

yes on file MainApplication, add `new MidtransPackage()`.

or you can link this library to your project

`react-native link react-native-payment-gateway`
