### ISSUE TITLE
Enable specific payment (ie: bank transfer only)

### ISSUE THREAD

**Issue by Dhaninovic** [aldente05/react-native-payment-gateway#9]
How I can enabled specific payment ? for example I only want to accept ATM/bank transfer only in my apps, so in midtrans I need to hide other payment method, thank you

**Comment by snelanga** [comment]
You can edit the payment channels on Midtrans Dashboard.
Goto **Snap Preference > Payment Channels** by expanding settings tab.
This feature sometimes has to be activated by contacting the support.
